<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StockCompanies;

class StockCompaniesSeeder extends Seeder
{
/**
 * Run the database seeds.
 *
 * @return void
 */
public function run()
{
    StockCompanies::create(['symbol' => '786', 'company_name' => '786 Investments Ltd']);
    StockCompanies::create(['symbol' => 'AABS', 'company_name' => 'AL-Abbas Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'ABL', 'company_name' => 'Allied Bank Ltd']);
    StockCompanies::create(['symbol' => 'ABOT', 'company_name' => 'Abbott Lab (Pakistan) Ltd']);
    StockCompanies::create(['symbol' => 'ACIETF', 'company_name' => 'Alfalah Consumer Index ETF']);
    StockCompanies::create(['symbol' => 'ACPL', 'company_name' => 'Attock Cement Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'ADAMS', 'company_name' => 'Adam Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'ADMM', 'company_name' => 'Artistic Denim Mills Ltd']);
    StockCompanies::create(['symbol' => 'ADOS', 'company_name' => 'Ados Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'AGHA', 'company_name' => 'Agha Steel Ind.Ltd']);
    StockCompanies::create(['symbol' => 'AGIC', 'company_name' => 'Askari General Insurance Co.']);
    StockCompanies::create(['symbol' => 'AGIL', 'company_name' => 'Agriauto Industries Ltd']);
    StockCompanies::create(['symbol' => 'AGL', 'company_name' => 'Agritech Limited']);
    StockCompanies::create(['symbol' => 'AGLNCPS', 'company_name' => 'Agritech Non-Voting (Pref)']);
    StockCompanies::create(['symbol' => 'AGP', 'company_name' => 'AGP Limited.']);
    StockCompanies::create(['symbol' => 'AGSML', 'company_name' => 'Abdullah Shah Ghazi Sugar']);
    StockCompanies::create(['symbol' => 'AGTL', 'company_name' => 'Al-Ghazi Tractors Ltd']);
    StockCompanies::create(['symbol' => 'AHCL', 'company_name' => 'Arif Habib Corporation Ltd']);
    StockCompanies::create(['symbol' => 'AHL', 'company_name' => 'Arif Habib Limited.']);
    StockCompanies::create(['symbol' => 'AHTM', 'company_name' => 'Ahmad Hassan Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'AICL', 'company_name' => 'Adamjee Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'AIRLINK', 'company_name' => 'Air Link Communication.']);
    StockCompanies::create(['symbol' => 'AKBL', 'company_name' => 'Askari Bank Ltd']);
    StockCompanies::create(['symbol' => 'AKDHL', 'company_name' => 'AKD Hospitality Limited']);
    StockCompanies::create(['symbol' => 'AKGL', 'company_name' => 'AL-Khair Gadoon Ltd']);
    StockCompanies::create(['symbol' => 'ALAC', 'company_name' => 'Askari Life Assurance Co.']);
    StockCompanies::create(['symbol' => 'ALIFE', 'company_name' => 'Adamjee Life Assu.Co.Ltd']);
    StockCompanies::create(['symbol' => 'ALNRS', 'company_name' => 'AL-Noor Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'ALTN', 'company_name' => 'Altern Energy Ltd']);
    StockCompanies::create(['symbol' => 'AMBL', 'company_name' => 'Apna Microfinance Bank Ltd']);
    StockCompanies::create(['symbol' => 'ANL', 'company_name' => 'Azgard Nine Ltd']);
    StockCompanies::create(['symbol' => 'ANLNV', 'company_name' => 'Azgard Nine (Non-Voting)']);
    StockCompanies::create(['symbol' => 'ANLPS', 'company_name' => 'Azgard Nine (Pref) 8.95%']);
    StockCompanies::create(['symbol' => 'ANTM', 'company_name' => 'AN Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'APL', 'company_name' => 'Attock Petroleum Ltd']);
    StockCompanies::create(['symbol' => 'ARCTM', 'company_name' => 'Arctic Textile Mills']);
    StockCompanies::create(['symbol' => 'ARM', 'company_name' => 'Allied Rental Modaraba.']);
    StockCompanies::create(['symbol' => 'ARPAK', 'company_name' => 'Arpak International Investments']);
    StockCompanies::create(['symbol' => 'ARPL', 'company_name' => 'Archroma Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'ARUJ', 'company_name' => 'Aruj Industries Ltd']);
    StockCompanies::create(['symbol' => 'ASC', 'company_name' => 'Al Shaheer Corporation Ltd']);
    StockCompanies::create(['symbol' => 'ASHT', 'company_name' => 'Ashfaq Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'ASIC', 'company_name' => 'Asia Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'ASL', 'company_name' => 'Aisha Steel Mills Ltd']);
    StockCompanies::create(['symbol' => 'ASLCPS', 'company_name' => 'Aisha Steel (Convt Pref)']);
    StockCompanies::create(['symbol' => 'ASLPS', 'company_name' => 'Aisha Steel (Preference)']);
    StockCompanies::create(['symbol' => 'ASTL', 'company_name' => 'Amreli Steels Ltd']);
    StockCompanies::create(['symbol' => 'ASTM', 'company_name' => 'Asim Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'ATBA', 'company_name' => 'Atlas Battery Ltd']);
    StockCompanies::create(['symbol' => 'ATIL', 'company_name' => 'Atlas Insurance Ltd']);
    StockCompanies::create(['symbol' => 'ATLH', 'company_name' => 'Atlas Honda Ltd']);
    StockCompanies::create(['symbol' => 'ATRL', 'company_name' => 'Attock Refinery Ltd']);
    StockCompanies::create(['symbol' => 'AVN', 'company_name' => 'Avanceon Limited.']);
    StockCompanies::create(['symbol' => 'AWTX', 'company_name' => 'Allawasaya Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'AWWAL', 'company_name' => 'Awwal Modaraba.']);
    StockCompanies::create(['symbol' => 'BAFL', 'company_name' => 'Bank Alfalah Ltd']);
    StockCompanies::create(['symbol' => 'BAFS', 'company_name' => 'Baba Farid Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'BAHL', 'company_name' => 'Bank AL Habib Ltd']);
    StockCompanies::create(['symbol' => 'BATA', 'company_name' => 'Bata (Pakistan) Ltd']);
    StockCompanies::create(['symbol' => 'BCL', 'company_name' => 'Bolan Castings Ltd']);
    StockCompanies::create(['symbol' => 'BECO', 'company_name' => 'BECO Steel Ltd']);
    StockCompanies::create(['symbol' => 'BERG', 'company_name' => 'Berger Paints Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'BFMOD', 'company_name' => 'B.F. Modaraba.']);
    StockCompanies::create(['symbol' => 'BGL', 'company_name' => 'Balochistan Glass Ltd']);
    StockCompanies::create(['symbol' => 'BHAT', 'company_name' => 'Bhanero Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'BIFO', 'company_name' => 'Biafo Industries Ltd']);
    StockCompanies::create(['symbol' => 'BIPL', 'company_name' => 'BankIslami Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'BIPLS', 'company_name' => 'BIPL Securities Limited.']);
    StockCompanies::create(['symbol' => 'BNL', 'company_name' => 'Bunny\'s Limited']);
    StockCompanies::create(['symbol' => 'BNWM', 'company_name' => 'Bannu Woollen Mills Ltd']);
    StockCompanies::create(['symbol' => 'BOK', 'company_name' => 'Bank of Khyber.']);
    StockCompanies::create(['symbol' => 'BOP', 'company_name' => 'Bank of Punjab.']);
    StockCompanies::create(['symbol' => 'BPL', 'company_name' => 'Burshane LPG (Pakistan)']);
    StockCompanies::create(['symbol' => 'BRR', 'company_name' => 'B.R.R Guardian Mod.']);
    StockCompanies::create(['symbol' => 'BTL', 'company_name' => 'Blessed Textiles Limited.']);
    StockCompanies::create(['symbol' => 'BUXL', 'company_name' => 'Buxly Paints Ltd']);
    StockCompanies::create(['symbol' => 'BWCL', 'company_name' => 'Bestway Cement Ltd']);
    StockCompanies::create(['symbol' => 'BWHL', 'company_name' => 'Baluchistan Wheels Ltd']);
    StockCompanies::create(['symbol' => 'CASH', 'company_name' => 'CALCORP Limited.']);
    StockCompanies::create(['symbol' => 'CCM', 'company_name' => 'Crescent Cotton Mills Ltd']);
    StockCompanies::create(['symbol' => 'CENI', 'company_name' => 'Century Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'CEPB', 'company_name' => 'Century Paper & Board Mills.']);
    StockCompanies::create(['symbol' => 'CFL', 'company_name' => 'Crescent Fibres Ltd']);
    StockCompanies::create(['symbol' => 'CHAS', 'company_name' => 'Chashma Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'CHCC', 'company_name' => 'Cherat Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'CLOV', 'company_name' => 'Clover Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'CLVL', 'company_name' => 'Cordoba Log. & Vent. LtdXR']);
    StockCompanies::create(['symbol' => 'CNERGY', 'company_name' => 'Cnergyico PK Ltd']);
    StockCompanies::create(['symbol' => 'COLG', 'company_name' => 'Colgate-Palmolive (Pakistan).']);
    StockCompanies::create(['symbol' => 'CPHL', 'company_name' => 'Citi Pharma Ltd']);
    StockCompanies::create(['symbol' => 'CPPL', 'company_name' => 'Cherat Packaging Ltd']);
    StockCompanies::create(['symbol' => 'CRTM', 'company_name' => 'Crescent Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'CSAP', 'company_name' => 'Crescent Steel & Allied Products']);
    StockCompanies::create(['symbol' => 'CSIL', 'company_name' => 'Crescent Star Insurance Ltd']);
    StockCompanies::create(['symbol' => 'CTM', 'company_name' => 'Colony Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'CYAN', 'company_name' => 'Cyan Limited.']);
    StockCompanies::create(['symbol' => 'DAAG', 'company_name' => 'Data Agro Ltd']);
    StockCompanies::create(['symbol' => 'DADX', 'company_name' => 'Dadex Eternit Ltd']);
    StockCompanies::create(['symbol' => 'DAWH', 'company_name' => 'Dawood Hercules Corporation.']);
    StockCompanies::create(['symbol' => 'DCL', 'company_name' => 'Dewan Cement Ltd']);
    StockCompanies::create(['symbol' => 'DCR', 'company_name' => 'Dolmen City REIT.']);
    StockCompanies::create(['symbol' => 'DEL', 'company_name' => 'Dawood Equities Ltd']);
    StockCompanies::create(['symbol' => 'DFSM', 'company_name' => 'Dewan Farooque Spinning']);
    StockCompanies::create(['symbol' => 'DGKC', 'company_name' => 'D.G. Khan Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'DIIL', 'company_name' => 'Diamond Industries Ltd']);
    StockCompanies::create(['symbol' => 'DINT', 'company_name' => 'Din Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'DLL', 'company_name' => 'Dawood Lawrencepur Ltd']);
    StockCompanies::create(['symbol' => 'DOL', 'company_name' => 'Descon Oxychem Ltd']);
    StockCompanies::create(['symbol' => 'DSIL', 'company_name' => 'D. S. Industries Ltd']);
    StockCompanies::create(['symbol' => 'DYNO', 'company_name' => 'Dynea Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'ECOP', 'company_name' => 'EcoPack Ltd']);
    StockCompanies::create(['symbol' => 'EFERT', 'company_name' => 'Engro Fertilizers Ltd']);
    StockCompanies::create(['symbol' => 'EFGH', 'company_name' => 'EFG Hermes Pakistan']);
    StockCompanies::create(['symbol' => 'EFUG', 'company_name' => 'EFU General Insurance Ltd']);
    StockCompanies::create(['symbol' => 'EFUL', 'company_name' => 'EFU Life Assurance Ltd']);
    StockCompanies::create(['symbol' => 'ELCM', 'company_name' => 'Elahi Cotton Mills Ltd']);
    StockCompanies::create(['symbol' => 'ELSM', 'company_name' => 'Ellcot Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'EMCO', 'company_name' => 'Emco Industries Ltd']);
    StockCompanies::create(['symbol' => 'ENGRO', 'company_name' => 'Engro Corporation Ltd']);
    StockCompanies::create(['symbol' => 'EPCL', 'company_name' => 'Engro Polymer & Chemicals.']);
    StockCompanies::create(['symbol' => 'EPCLPS', 'company_name' => 'Engro Plymer Preference.']);
    StockCompanies::create(['symbol' => 'EPQL', 'company_name' => 'Engro Powergen Qadirpur Ltd']);
    StockCompanies::create(['symbol' => 'ESBL', 'company_name' => 'Escorts Investment Bank Ltd']);
    StockCompanies::create(['symbol' => 'EWIC', 'company_name' => 'East West Insurance Co.']);
    StockCompanies::create(['symbol' => 'EWICR2', 'company_name' => 'East West Insurance (R)']);
    StockCompanies::create(['symbol' => 'EXIDE', 'company_name' => 'Exide Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'FABL', 'company_name' => 'Faysal Bank Ltd']);
    StockCompanies::create(['symbol' => 'FANM', 'company_name' => 'AL-Noor Modaraba 1st']);
    StockCompanies::create(['symbol' => 'FASM', 'company_name' => 'Faisal Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'FATIMA', 'company_name' => 'Fatima Fertilizer Company Ltd']);
    StockCompanies::create(['symbol' => 'FCCL', 'company_name' => 'Fauji Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'FCEPL', 'company_name' => 'Frieslandcampina Engro Pakistan']);
    StockCompanies::create(['symbol' => 'FCIBL', 'company_name' => 'First Credit & Investment Bank Ltd']);
    StockCompanies::create(['symbol' => 'FCONM', 'company_name' => 'Constellation Modaraba 1st']);
    StockCompanies::create(['symbol' => 'FCSC', 'company_name' => 'First Capital Securities Corp. Ltd']);
    StockCompanies::create(['symbol' => 'FDIBL', 'company_name' => 'First Dawood Investment Bank Ltd']);
    StockCompanies::create(['symbol' => 'FECM', 'company_name' => 'Elite Capital Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FECTC', 'company_name' => 'Fecto Cement Ltd']);
    StockCompanies::create(['symbol' => 'FEM', 'company_name' => 'Equity Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FEROZ', 'company_name' => 'Ferozsons Laboratories Ltd']);
    StockCompanies::create(['symbol' => 'FFBL', 'company_name' => 'Fauji Fertilizer Bin Qasim Ltd']);
    StockCompanies::create(['symbol' => 'FFC', 'company_name' => 'Fauji Fertilizer Company Ltd']);
    StockCompanies::create(['symbol' => 'FFL', 'company_name' => 'Fauji Foods Limited.']);
    StockCompanies::create(['symbol' => 'FFLM', 'company_name' => 'First Fidelity Leasing Modaraba']);
    StockCompanies::create(['symbol' => 'FHAM', 'company_name' => 'Habib Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FIBLM', 'company_name' => 'IBL Modaraba 1st']);
    StockCompanies::create(['symbol' => 'FIMM', 'company_name' => 'Imrooz Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FLYNG', 'company_name' => 'Flying Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'FML', 'company_name' => 'Feroze1888 Mills Ltd']);
    StockCompanies::create(['symbol' => 'FNEL', 'company_name' => 'First National Equities Ltd']);
    StockCompanies::create(['symbol' => 'FPJM', 'company_name' => 'Punjab Modaraba 1st']);
    StockCompanies::create(['symbol' => 'FPRM', 'company_name' => 'Paramount Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FRCL', 'company_name' => 'Frontier Ceramics Ltd']);
    StockCompanies::create(['symbol' => 'FRSM', 'company_name' => 'Faran Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'FTMM', 'company_name' => 'First Treet Mfg Modaraba']);
    StockCompanies::create(['symbol' => 'FTSM', 'company_name' => 'Tri-Star Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FUDLM', 'company_name' => 'U.D.L. Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'FZCM', 'company_name' => 'Fazal Cloth Mills Ltd']);
    StockCompanies::create(['symbol' => 'GADT', 'company_name' => 'Gadoon Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'GAMON', 'company_name' => 'Gammon Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'GATI', 'company_name' => 'Gatron (Industries) Ltd']);
    StockCompanies::create(['symbol' => 'GATM', 'company_name' => 'Gul Ahmed Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'GFIL', 'company_name' => 'Ghazi Fabrics International Ltd']);
    StockCompanies::create(['symbol' => 'GGGL', 'company_name' => 'Ghani Global Glass Ltd']);
    StockCompanies::create(['symbol' => 'GGL', 'company_name' => 'Ghani Global Holdings.']);
    StockCompanies::create(['symbol' => 'GHGL', 'company_name' => 'Ghani Glass Ltd']);
    StockCompanies::create(['symbol' => 'GHNI', 'company_name' => 'Ghandhara Industries Ltd']);
    StockCompanies::create(['symbol' => 'GHNL', 'company_name' => 'Ghandhara Nissan Ltd']);
    StockCompanies::create(['symbol' => 'GIL', 'company_name' => 'Goodluck Industries Ltd']);
    StockCompanies::create(['symbol' => 'GLAXO', 'company_name' => 'GlaxoSmithKline Pakistan.']);
    StockCompanies::create(['symbol' => 'GLPL', 'company_name' => 'Gillette Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'GOC', 'company_name' => 'GOC (Pak) Limited']);
    StockCompanies::create(['symbol' => 'GRYL', 'company_name' => 'Grays Leasing Ltd']);
    StockCompanies::create(['symbol' => 'GSKCH', 'company_name' => 'GlaxoSmithKline Consumer Healthcare']);
    StockCompanies::create(['symbol' => 'GTECH', 'company_name' => 'G3 Technologies Ltd']);
    StockCompanies::create(['symbol' => 'GTYR', 'company_name' => 'Ghandhara Tyre & Rubber Co.']);
    StockCompanies::create(['symbol' => 'GVGL', 'company_name' => 'Ghani Value Glass Ltd']);
    StockCompanies::create(['symbol' => 'GWLC', 'company_name' => 'Gharibwal Cement Ltd']);
    StockCompanies::create(['symbol' => 'HABSM', 'company_name' => 'Habib Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'HAEL', 'company_name' => 'Hala Enterprises Ltd']);
    StockCompanies::create(['symbol' => 'HAFL', 'company_name' => 'Hafiz Limited.']);
    StockCompanies::create(['symbol' => 'HBL', 'company_name' => 'Habib Bank Ltd']);
    StockCompanies::create(['symbol' => 'HCAR', 'company_name' => 'Honda Atlas Cars (Pakistan) LtdXD']);
    StockCompanies::create(['symbol' => 'HCL', 'company_name' => 'Hallmark Company']);
    StockCompanies::create(['symbol' => 'HGFA', 'company_name' => 'HBL Growth Fund - (A)']);
    StockCompanies::create(['symbol' => 'HICL', 'company_name' => 'Habib Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'HIFA', 'company_name' => 'HBL Investment Fund - (A)']);
    StockCompanies::create(['symbol' => 'HINO', 'company_name' => 'Hinopak Motors Ltd']);
    StockCompanies::create(['symbol' => 'HINOON', 'company_name' => 'Highnoon Laboratories Ltd']);
    StockCompanies::create(['symbol' => 'HMB', 'company_name' => 'Habib Metropolitan Bank Ltd']);
    StockCompanies::create(['symbol' => 'HMM', 'company_name' => 'Habib Metro Modaraba.']);
    StockCompanies::create(['symbol' => 'HRPL', 'company_name' => 'Habib Rice Prud.']);
    StockCompanies::create(['symbol' => 'HSM', 'company_name' => 'Husein Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'HSMCPS', 'company_name' => 'Husein Sugar Mills (Preference Shares)']);
    StockCompanies::create(['symbol' => 'HTL', 'company_name' => 'Hi-Tech Lubricants Ltd']);
    StockCompanies::create(['symbol' => 'HUBC', 'company_name' => 'Hub Power Company Ltd']);
    StockCompanies::create(['symbol' => 'HUMNL', 'company_name' => 'Hum Network Ltd']);
    StockCompanies::create(['symbol' => 'HUSI', 'company_name' => 'Husein Industries']);
    StockCompanies::create(['symbol' => 'IBFL', 'company_name' => 'Ibrahim Fibres Ltd']);
    StockCompanies::create(['symbol' => 'IBLHL', 'company_name' => 'IBL HealthCare Ltd']);
    StockCompanies::create(['symbol' => 'ICI', 'company_name' => 'I. C. I. Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'ICIBL', 'company_name' => 'Invest Capital Investment Bank']);
    StockCompanies::create(['symbol' => 'ICL', 'company_name' => 'Ittehad Chemicals Ltd']);
    StockCompanies::create(['symbol' => 'IDRT', 'company_name' => 'Idrees Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'IDSM', 'company_name' => 'Ideal Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'IDYM', 'company_name' => 'Indus Dyeing & Mfg Co. Ltd']);
    StockCompanies::create(['symbol' => 'IGIHL', 'company_name' => 'IGI Holdings Ltd']);
    StockCompanies::create(['symbol' => 'IGIL', 'company_name' => 'IGI Life Insurance Ltd']);
    StockCompanies::create(['symbol' => 'ILP', 'company_name' => 'Interloop Limited.']);
    StockCompanies::create(['symbol' => 'IMAGE', 'company_name' => 'Image Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'IML', 'company_name' => 'Imperial Ltd']);
    StockCompanies::create(['symbol' => 'INDU', 'company_name' => 'Indus Motor Company Ltd']);
    StockCompanies::create(['symbol' => 'INIL', 'company_name' => 'International Industries Ltd']);
    StockCompanies::create(['symbol' => 'INKL', 'company_name' => 'International Knitwear Ltd']);
    StockCompanies::create(['symbol' => 'ISIL', 'company_name' => 'Ismail Industries Ltd']);
    StockCompanies::create(['symbol' => 'ISL', 'company_name' => 'International Steels Ltd']);
    StockCompanies::create(['symbol' => 'ITTEFAQ', 'company_name' => 'Ittefaq Iron Industries']);
    StockCompanies::create(['symbol' => 'JATM', 'company_name' => 'J.A.Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'JDMT', 'company_name' => 'Janana De Malucho Textile']);
    StockCompanies::create(['symbol' => 'JDWS', 'company_name' => 'JDW Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'JGICL', 'company_name' => 'Jubilee General Insurance Co.']);
    StockCompanies::create(['symbol' => 'JKSM', 'company_name' => 'J.K.Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'JLICL', 'company_name' => 'Jubilee Life Insurance Co.']);
    StockCompanies::create(['symbol' => 'JOPP', 'company_name' => 'Johnson & Phillips (Pakistan) Ltd']);
    StockCompanies::create(['symbol' => 'JSBL', 'company_name' => 'JS Bank Ltd']);
    StockCompanies::create(['symbol' => 'JSCL', 'company_name' => 'Jahangir Siddiqui & Co. Ltd']);
    StockCompanies::create(['symbol' => 'JSCLPSA', 'company_name' => 'Jahangir Siddiqui Preference Share.']);
    StockCompanies::create(['symbol' => 'JSGCL', 'company_name' => 'JS Global Capital Ltd']);
    StockCompanies::create(['symbol' => 'JSIL', 'company_name' => 'JS Investments Ltd']);
    StockCompanies::create(['symbol' => 'JSMFETF', 'company_name' => 'JS Momentum Factor ETF']);
    StockCompanies::create(['symbol' => 'JSML', 'company_name' => 'Jauharabad Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'JVDC', 'company_name' => 'Javedan Corporation Ltd']);
    StockCompanies::create(['symbol' => 'JVDCPS', 'company_name' => 'Javedan Corp Preference']);
    StockCompanies::create(['symbol' => 'KAPCO', 'company_name' => 'Kot Addu Power Company.']);
    StockCompanies::create(['symbol' => 'KASBM', 'company_name' => 'KASB Modaraba.']);
    StockCompanies::create(['symbol' => 'KCL', 'company_name' => 'Karam Ceramics Ltd']);
    StockCompanies::create(['symbol' => 'KEL', 'company_name' => 'K-Electric Ltd']);
    StockCompanies::create(['symbol' => 'KHTC', 'company_name' => 'Khyber Tobacco Company']);
    StockCompanies::create(['symbol' => 'KHYT', 'company_name' => 'Khyber Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'KML', 'company_name' => 'Kohinoor Mills Ltd']);
    StockCompanies::create(['symbol' => 'KOHC', 'company_name' => 'Kohat Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'KOHE', 'company_name' => 'Kohinoor Energy Ltd']);
    StockCompanies::create(['symbol' => 'KOHP', 'company_name' => 'Kohinoor Power Company']);
    StockCompanies::create(['symbol' => 'KOHTM', 'company_name' => 'Kohat Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'KOIL', 'company_name' => 'Kohinoor Industries Ltd']);
    StockCompanies::create(['symbol' => 'KOSM', 'company_name' => 'Kohinoor Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'KPUS', 'company_name' => 'Khairpur Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'KSBP', 'company_name' => 'K.S.B.Pumps Company Ltd']);
    StockCompanies::create(['symbol' => 'KTML', 'company_name' => 'Kohinoor Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'LEUL', 'company_name' => 'Leather-Up Ltd']);
    StockCompanies::create(['symbol' => 'LOADS', 'company_name' => 'Loads Limited']);
    StockCompanies::create(['symbol' => 'LOTCHEM', 'company_name' => 'Lotte Chemical Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'LPGL', 'company_name' => 'Leiner Pak Gelatine Ltd']);
    StockCompanies::create(['symbol' => 'LPL', 'company_name' => 'Lalpir Power Ltd']);
    StockCompanies::create(['symbol' => 'LUCK', 'company_name' => 'Lucky Cement Ltd']);
    StockCompanies::create(['symbol' => 'MACFL', 'company_name' => 'MACPAC Films Ltd']);
    StockCompanies::create(['symbol' => 'MACTER', 'company_name' => 'Macter International Ltd']);
    StockCompanies::create(['symbol' => 'MARI', 'company_name' => 'Mari Petroleum Co. Ltd']);
    StockCompanies::create(['symbol' => 'MCB', 'company_name' => 'MCB Bank Ltd']);
    StockCompanies::create(['symbol' => 'MCBAH', 'company_name' => 'MCB-Arif Habib Savings & Inv.']);
    StockCompanies::create(['symbol' => 'MDTL', 'company_name' => 'Media Times Ltd']);
    StockCompanies::create(['symbol' => 'MEBL', 'company_name' => 'Meezan Bank Ltd']);
    StockCompanies::create(['symbol' => 'MEHT', 'company_name' => 'Mahmood Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'MERIT', 'company_name' => 'Merit Packaging Ltd']);
    StockCompanies::create(['symbol' => 'MFFL', 'company_name' => 'Mitchell\'s Fruit Farms Ltd']);
    StockCompanies::create(['symbol' => 'MFL', 'company_name' => 'Matco Foods Limited']);
    StockCompanies::create(['symbol' => 'MIRKS', 'company_name' => 'Mirpurkhas Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'MLCF', 'company_name' => 'Maple Leaf Cement Factory']);
    StockCompanies::create(['symbol' => 'MODAM', 'company_name' => 'Modaraba Al-Mali']);
    StockCompanies::create(['symbol' => 'MQTM', 'company_name' => 'Maqbool Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'MRNS', 'company_name' => 'Mehran Sugar Mills LtdXB']);
    StockCompanies::create(['symbol' => 'MSCL', 'company_name' => 'Metropolitan Steel Corp.']);
    StockCompanies::create(['symbol' => 'MSOT', 'company_name' => 'Masood Textile Mills']);
    StockCompanies::create(['symbol' => 'MSOTPS', 'company_name' => 'Masood Textile Mills Preference.']);
    StockCompanies::create(['symbol' => 'MTL', 'company_name' => 'Millat Tractors Ltd']);
    StockCompanies::create(['symbol' => 'MUGHAL', 'company_name' => 'Mughal Iron & Steel Industries.']);
    StockCompanies::create(['symbol' => 'MUREB', 'company_name' => 'Murree Brewery Company.']);
    StockCompanies::create(['symbol' => 'MZNPETF', 'company_name' => 'Meezan Pakistan.']);
    StockCompanies::create(['symbol' => 'NAGC', 'company_name' => 'Nagina Cotton Mills Ltd']);
    StockCompanies::create(['symbol' => 'NATF', 'company_name' => 'National Foods Ltd']);
    StockCompanies::create(['symbol' => 'NATM', 'company_name' => 'Nadeem Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'NBP', 'company_name' => 'National Bank of Pakistan.XD']);
    StockCompanies::create(['symbol' => 'NBPGETF', 'company_name' => 'NBP Pakistan Growth']);
    StockCompanies::create(['symbol' => 'NCL', 'company_name' => 'Nishat (Chunian) Ltd']);
    StockCompanies::create(['symbol' => 'NCPL', 'company_name' => 'Nishat Chunian Power Ltd']);
    StockCompanies::create(['symbol' => 'NESTLE', 'company_name' => 'Nestle Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'NETSOL', 'company_name' => 'NetSol Technologies Ltd']);
    StockCompanies::create(['symbol' => 'NEXT', 'company_name' => 'Next Capital Limited']);
    StockCompanies::create(['symbol' => 'NICL', 'company_name' => 'Nimir Industrial Chemicals Ltd']);
    StockCompanies::create(['symbol' => 'NITGETF', 'company_name' => 'NIT Pakistan Gateway.']);
    StockCompanies::create(['symbol' => 'NML', 'company_name' => 'Nishat Mills Ltd']);
    StockCompanies::create(['symbol' => 'NONS', 'company_name' => 'Noon Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'NPL', 'company_name' => 'Nishat Power Ltd']);
    StockCompanies::create(['symbol' => 'NRL', 'company_name' => 'National Refinery Ltd']);
    StockCompanies::create(['symbol' => 'NRSL', 'company_name' => 'Nimir Resins Ltd']);
    StockCompanies::create(['symbol' => 'NSRM', 'company_name' => 'National Silk & Rayon Mills']);
    StockCompanies::create(['symbol' => 'OBOY', 'company_name' => 'Oilboy Energy Ltd']);
    StockCompanies::create(['symbol' => 'OBOYR1', 'company_name' => 'Oilboy Energy Limited (R)']);
    StockCompanies::create(['symbol' => 'OCTOPUS', 'company_name' => 'Octopus Digital Ltd']);
    StockCompanies::create(['symbol' => 'OGDC', 'company_name' => 'Oil & Gas Development Co. Ltd']);
    StockCompanies::create(['symbol' => 'OLPL', 'company_name' => 'OLP Financial Services Pak. Ltd']);
    StockCompanies::create(['symbol' => 'OLPM', 'company_name' => 'OLP Modaraba.']);
    StockCompanies::create(['symbol' => 'OML', 'company_name' => 'Olympia Mills Limited']);
    StockCompanies::create(['symbol' => 'ORM', 'company_name' => 'Orient Rental Modaraba.']);
    StockCompanies::create(['symbol' => 'OTSU', 'company_name' => 'Otsuka Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'PABC', 'company_name' => 'Pakistan Aluminium Beverage Cans Ltd']);
    StockCompanies::create(['symbol' => 'PACE', 'company_name' => 'Pace (Pakistan) Limited']);
    StockCompanies::create(['symbol' => 'PAEL', 'company_name' => 'Pak Elektron Ltd']);
    StockCompanies::create(['symbol' => 'PAKD', 'company_name' => 'Pak Datacom Ltd']);
    StockCompanies::create(['symbol' => 'PAKMI', 'company_name' => 'Pak Modaraba 1st']);
    StockCompanies::create(['symbol' => 'PAKOXY', 'company_name' => 'Pakistan Oxygen Ltd']);
    StockCompanies::create(['symbol' => 'PAKRI', 'company_name' => 'Pakistan Reinsurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'PAKT', 'company_name' => 'Pakistan Tobacco Co.']);
    StockCompanies::create(['symbol' => 'PCAL', 'company_name' => 'Pakistan Cables Ltd']);
    StockCompanies::create(['symbol' => 'PELPS', 'company_name' => 'Pak Elektron Ltd Preference']);
    StockCompanies::create(['symbol' => 'PGLC', 'company_name' => 'Pak- Gulf Leasing Company']);
    StockCompanies::create(['symbol' => 'PHDL', 'company_name' => 'Pakistan Hotels Developers.']);
    StockCompanies::create(['symbol' => 'PIAA', 'company_name' => 'P.I.A.C.L. "A"']);
    StockCompanies::create(['symbol' => 'PIAB', 'company_name' => 'P.I.A.C.L "B"']);
    StockCompanies::create(['symbol' => 'PIBTL', 'company_name' => 'Pakistan Int Bulk Terminal Ltd']);
    StockCompanies::create(['symbol' => 'PICT', 'company_name' => 'Pakistan Int. Container Terminal.']);
    StockCompanies::create(['symbol' => 'PIM', 'company_name' => 'Popular Islamic Modaraba.']);
    StockCompanies::create(['symbol' => 'PINL', 'company_name' => 'Premier Insurance Ltd']);
    StockCompanies::create(['symbol' => 'PIOC', 'company_name' => 'Pioneer Cement Ltd']);
    StockCompanies::create(['symbol' => 'PKGP', 'company_name' => 'Pakgen Power Ltd']);
    StockCompanies::create(['symbol' => 'PKGS', 'company_name' => 'Packages Limited.']);
    StockCompanies::create(['symbol' => 'PMI', 'company_name' => 'Prudential Modaraba 1st.']);
    StockCompanies::create(['symbol' => 'PMPK', 'company_name' => 'Philip Morris (Pakistan) Ltd']);
    StockCompanies::create(['symbol' => 'PMRS', 'company_name' => 'Premier Sugar Mills & Distillery Co. Ltd']);
    StockCompanies::create(['symbol' => 'PNSC', 'company_name' => 'P. N. S. C.']);
    StockCompanies::create(['symbol' => 'POL', 'company_name' => 'Pakistan Oilfields Ltd']);
    StockCompanies::create(['symbol' => 'POML', 'company_name' => 'Punjab Oil Mills Ltd']);
    StockCompanies::create(['symbol' => 'POWER', 'company_name' => 'Power Cement Ltd']);
    StockCompanies::create(['symbol' => 'POWERPS', 'company_name' => 'Power Cement Preference']);
    StockCompanies::create(['symbol' => 'PPL', 'company_name' => 'Pakistan Petroleum Ltd']);
    StockCompanies::create(['symbol' => 'PPLPS', 'company_name' => 'Pakistan Petroleum (Preference)']);
    StockCompanies::create(['symbol' => 'PPP', 'company_name' => 'Pakistan Paper Products Ltd']);
    StockCompanies::create(['symbol' => 'PREMA', 'company_name' => 'At-Tahur Ltd']);
    StockCompanies::create(['symbol' => 'PRET', 'company_name' => 'Premium Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'PRL', 'company_name' => 'Pakistan Refinery Ltd']);
    StockCompanies::create(['symbol' => 'PRWM', 'company_name' => 'Prosperity Weaving Mills Ltd']);
    StockCompanies::create(['symbol' => 'PSEL', 'company_name' => 'Pakistan Services Ltd']);
    StockCompanies::create(['symbol' => 'PSMC', 'company_name' => 'Pak Suzuki Motor Co. Ltd']);
    StockCompanies::create(['symbol' => 'PSO', 'company_name' => 'Pakistan State Oil Co. Ltd']);
    StockCompanies::create(['symbol' => 'PSX', 'company_name' => 'Pakistan Stock Exchange Ltd']);
    StockCompanies::create(['symbol' => 'PSYL', 'company_name' => 'Pakistan Synthetics Ltd']);
    StockCompanies::create(['symbol' => 'PTC', 'company_name' => 'P.T.C.L. "A"']);
    StockCompanies::create(['symbol' => 'PTCB', 'company_name' => 'P.T.C.L. "B"']);
    StockCompanies::create(['symbol' => 'PTL', 'company_name' => 'Panther Tyres Ltd']);
    StockCompanies::create(['symbol' => 'QUET', 'company_name' => 'Quetta Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'RCML', 'company_name' => 'Reliance Cottton Spinning.']);
    StockCompanies::create(['symbol' => 'REDCO', 'company_name' => 'Redco Textiles Ltd']);
    StockCompanies::create(['symbol' => 'REWM', 'company_name' => 'Reliance Weaving Mills.']);
    StockCompanies::create(['symbol' => 'RICL', 'company_name' => 'Reliance Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'RMPL', 'company_name' => 'Rafhan Maize Products.']);
    StockCompanies::create(['symbol' => 'RPL', 'company_name' => 'Roshan Packages Ltd']);
    StockCompanies::create(['symbol' => 'RUPL', 'company_name' => 'Rupali Polyester Ltd']);
    StockCompanies::create(['symbol' => 'SAIF', 'company_name' => 'Saif Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'SANSM', 'company_name' => 'Sanghar Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'SAPL', 'company_name' => 'Sanofi-aventis Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'SAPT', 'company_name' => 'Sapphire Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'SARC', 'company_name' => 'Sardar Chemical Industries.']);
    StockCompanies::create(['symbol' => 'SASML', 'company_name' => 'Sindh Abadgar\'s Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'SAZEW', 'company_name' => 'Sazgar Engineering Works.']);
    StockCompanies::create(['symbol' => 'SBL', 'company_name' => 'Samba Bank Ltd']);
    StockCompanies::create(['symbol' => 'SCBPL', 'company_name' => 'Standard Chartered Bank Ltd']);
    StockCompanies::create(['symbol' => 'SCL', 'company_name' => 'Shield Corporation Ltd']);
    StockCompanies::create(['symbol' => 'SEARL', 'company_name' => 'The Searle Company Ltd']);
    StockCompanies::create(['symbol' => 'SEL', 'company_name' => 'Sitara Energy Ltd']);
    StockCompanies::create(['symbol' => 'SEPL', 'company_name' => 'Security Papers Ltd']);
    StockCompanies::create(['symbol' => 'SERT', 'company_name' => 'Service Textiles Industries Ltd']);
    StockCompanies::create(['symbol' => 'SFL', 'company_name' => 'Sapphire Fibres Ltd']);
    StockCompanies::create(['symbol' => 'SGABL', 'company_name' => 'SG Allied Businesses']);
    StockCompanies::create(['symbol' => 'SGF', 'company_name' => 'Service Global Footwear Ltd']);
    StockCompanies::create(['symbol' => 'SGPL', 'company_name' => 'S.G. Power Ltd']);
    StockCompanies::create(['symbol' => 'SHCM', 'company_name' => 'Shadman Cotton Mills']);
    StockCompanies::create(['symbol' => 'SHDT', 'company_name' => 'Shadab Textile Mills Ltd,']);
    StockCompanies::create(['symbol' => 'SHEL', 'company_name' => 'Shell (Pakistan) Ltd']);
    StockCompanies::create(['symbol' => 'SHEZ', 'company_name' => 'Shezan International Ltd']);
    StockCompanies::create(['symbol' => 'SHFA', 'company_name' => 'Shifa International Hospitals Ltd']);
    StockCompanies::create(['symbol' => 'SHJS', 'company_name' => 'Shahtaj Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'SHNI', 'company_name' => 'Shaheen Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'SHSML', 'company_name' => 'Shahmurad Sugar Mills Ltd']);
    StockCompanies::create(['symbol' => 'SIBL', 'company_name' => 'Security Investment Bank Ltd']);
    StockCompanies::create(['symbol' => 'SIEM', 'company_name' => 'Siemens (Pakistan) Engineering.']);
    StockCompanies::create(['symbol' => 'SILK', 'company_name' => 'Silkbank Ltd']);
    StockCompanies::create(['symbol' => 'SINDM', 'company_name' => 'Sindh Modaraba.']);
    StockCompanies::create(['symbol' => 'SITC', 'company_name' => 'Sitara Chemical Industries Ltd']);
    StockCompanies::create(['symbol' => 'SLCPA', 'company_name' => 'Security Leasing Corp.(Pref) 9.1%']);
    StockCompanies::create(['symbol' => 'SLL', 'company_name' => 'SME Leasing Ltd']);
    StockCompanies::create(['symbol' => 'SMBL', 'company_name' => 'Summit Bank Ltd']);
    StockCompanies::create(['symbol' => 'SMCPL', 'company_name' => 'Safe Mix Concrete Ltd']);
    StockCompanies::create(['symbol' => 'SML', 'company_name' => 'Shakarganj Limited']);
    StockCompanies::create(['symbol' => 'SMTM', 'company_name' => 'Samin Textiles Ltd']);
    StockCompanies::create(['symbol' => 'SNAI', 'company_name' => 'Sana Industries Ltd']);
    StockCompanies::create(['symbol' => 'SNBL', 'company_name' => 'Soneri Bank Ltd']);
    StockCompanies::create(['symbol' => 'SNGP', 'company_name' => 'Sui Northern Gas Pipelines.']);
    StockCompanies::create(['symbol' => 'SPEL', 'company_name' => 'Synthetic Products Ltd']);
    StockCompanies::create(['symbol' => 'SPL', 'company_name' => 'Sitara Peroxide Ltd']);
    StockCompanies::create(['symbol' => 'SPWL', 'company_name' => 'Saif Power Ltd']);
    StockCompanies::create(['symbol' => 'SRVI', 'company_name' => 'Service Industries Ltd']);
    StockCompanies::create(['symbol' => 'SSGC', 'company_name' => 'Sui Southern Gas Co. Ltd']);
    StockCompanies::create(['symbol' => 'SSML', 'company_name' => 'Saritow Spinning Mills Ltd']);
    StockCompanies::create(['symbol' => 'SSOM', 'company_name' => 'S.S.Oil Mills Ltd']);
    StockCompanies::create(['symbol' => 'STCL', 'company_name' => 'Shabbir Tiles & Ceramics Ltd']);
    StockCompanies::create(['symbol' => 'STJT', 'company_name' => 'Shahtaj Textile Limited.']);
    StockCompanies::create(['symbol' => 'STML', 'company_name' => 'Shams Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'STPL', 'company_name' => 'Siddiqsons Tin Plate Ltd']);
    StockCompanies::create(['symbol' => 'SURC', 'company_name' => 'Suraj Cotton Mills Ltd']);
    StockCompanies::create(['symbol' => 'SUTM', 'company_name' => 'Sunrays Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'SYS', 'company_name' => 'Systems Limited.']);
    StockCompanies::create(['symbol' => 'SZTM', 'company_name' => 'Shahzad Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'TATM', 'company_name' => 'Tata Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'TELE', 'company_name' => 'Telecard Limited.']);
    StockCompanies::create(['symbol' => 'TGL', 'company_name' => 'Tariq Glass Industries Ltd']);
    StockCompanies::create(['symbol' => 'THALL', 'company_name' => 'Thal Limited.']);
    StockCompanies::create(['symbol' => 'THCCL', 'company_name' => 'Thatta Cement Co. Ltd']);
    StockCompanies::create(['symbol' => 'TICL', 'company_name' => 'Thal Industries Corporation']);
    StockCompanies::create(['symbol' => 'TOMCL', 'company_name' => 'The Organic Meat Co.Ltd']);
    StockCompanies::create(['symbol' => 'TOWL', 'company_name' => 'Towellers Limited']);
    StockCompanies::create(['symbol' => 'TPL', 'company_name' => 'TPL Corp Limited']);
    StockCompanies::create(['symbol' => 'TPLI', 'company_name' => 'TPL Insurance Ltd']);
    StockCompanies::create(['symbol' => 'TPLP', 'company_name' => 'TPL Properties Ltd']);
    StockCompanies::create(['symbol' => 'TPLT', 'company_name' => 'TPL Trakker Ltd']);
    StockCompanies::create(['symbol' => 'TREET', 'company_name' => 'Treet Corporation Ltd']);
    StockCompanies::create(['symbol' => 'TRG', 'company_name' => 'TRG Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'TRIPF', 'company_name' => 'Tri-Pack Films LtdXD']);
    StockCompanies::create(['symbol' => 'TRSM', 'company_name' => 'Trust Modaraba']);
    StockCompanies::create(['symbol' => 'TSBL', 'company_name' => 'Trust Securities & Brokerage']);
    StockCompanies::create(['symbol' => 'TSMF', 'company_name' => 'Tri-Star Mutual Fund']);
    StockCompanies::create(['symbol' => 'TSPL', 'company_name' => 'Tri-Star Power Ltd']);
    StockCompanies::create(['symbol' => 'UBDL', 'company_name' => 'United Brands Ltd']);
    StockCompanies::create(['symbol' => 'UBL', 'company_name' => 'United Bank Ltd']);
    StockCompanies::create(['symbol' => 'UBLPETF', 'company_name' => 'UBL Pakistan Enterprise.XD']);
    StockCompanies::create(['symbol' => 'UCAPM', 'company_name' => 'Unicap Modaraba']);
    StockCompanies::create(['symbol' => 'UDPL', 'company_name' => 'United Distrbutors Pakistan Ltd']);
    StockCompanies::create(['symbol' => 'UNIC', 'company_name' => 'United Insurance Co. of Pakistan']);
    StockCompanies::create(['symbol' => 'UNITY', 'company_name' => 'Unity Foods Limited.']);
    StockCompanies::create(['symbol' => 'UPFL', 'company_name' => 'Unilever Pakistan Foods Ltd']);
    StockCompanies::create(['symbol' => 'UVIC', 'company_name' => 'Universal Insurance Co. Ltd']);
    StockCompanies::create(['symbol' => 'WAHN', 'company_name' => 'Wah-Noble Chemicals Ltd']);
    StockCompanies::create(['symbol' => 'WAVES', 'company_name' => 'Waves Singer Pakistan']);
    StockCompanies::create(['symbol' => 'WTL', 'company_name' => 'WorldCall Telecom Ltd']);
    StockCompanies::create(['symbol' => 'YOUW', 'company_name' => 'Yousaf Weaving Mills Ltd']);
    StockCompanies::create(['symbol' => 'ZAHID', 'company_name' => 'Zahidjee Textile Mills Ltd']);
    StockCompanies::create(['symbol' => 'ZIL', 'company_name' => 'ZIL Limited.']);
    StockCompanies::create(['symbol' => 'ZTL', 'company_name' => 'Zephyr Textiles Ltd']);
}
}
